In [ ]:
# When you read numpy , you are really doing two things
    # 1> reading the operations 
    # 2> keeping track of shapes

In [8]:
# VECTOR
import numpy as np 


a = np.array([1,2,3]) # Vector
print(a.shape)

b = np.array([4,5,6]) # Vector
print(b.shape)

(3,)
(3,)


In [3]:
# MATRIX
import numpy as np 

c = np.array([[1,2,3],
              [4,5,6]]) # Matrix

print(c.shape)

(2, 3)


In [5]:
# matrix of zeros 

d =np.zeros((2,4)) # 2 X 4 matrix of zeros 
print(d.shape) # (2, 4)

(2, 4)


In [7]:
# Random Matrix Between 0 and 1 



# e : is a variable name assigned to a NumPy array.

# np : is an alias for the NumPy module, which is a popular numerical computing library in Python.

# .random : is a sub-module in NumPy that contains functions for generating random numbers.

# .rand(2,5) : is a function in the random sub-module that generates a 2 by 5 array of random numbers between 0 and 1.

# Therefore, the code e = np.random.rand(2,5) creates a 2 by 5 NumPy array of random numbers between 0 and 1 and assigns it to the variable e.






e = np.random.rand(2,5) # Random 2 X 5 matrix of numbers between 0 and 1 
print(e)

[[0.31036018 0.77097294 0.92815441 0.22931635 0.23195757]
 [0.90000498 0.39570168 0.3381846  0.3135195  0.25871379]]


In [9]:
a = np.array([1,2,3]) # Vector
print(a*0.1) # Multiply every number in vector a by 0.1

[0.1 0.2 0.3]


In [10]:
import numpy as np 

c = np.array([[1,2,3],
              [4,5,6]]) # Matrix

print(c*0.2)  # Multiply every number in matrix c by 0.2

[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [12]:
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b) # Multiply elementwise between a and b (columns paired)


[ 4 10 18]


In [ ]:
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b * 0.2) # Multiply elementwise between a and b ,then multiply by 0.2


In [13]:
import numpy as np 

a = np.array([1,2,3]) # Vector

c = np.array([[1,2,3],
              [4,5,6]]) # Matrix

print(a*c) # Perform elementwise multiplication on every row of matrix c , because c has the same number
                # of column as a 

[[ 1  4  9]
 [ 4 10 18]]


In [14]:
import numpy as np 

a = np.array([1,2,3]) # Vector

e = np.random.rand(2,5) # Random 2 X 5 matrix of numbers between 0 and 1 
print(e)

print(a*e) # Because a and e don't have the same number of columns , this throws ,
              # "Value Error" -> operands could not be broadcast together with ....

[[0.18341913 0.23661143 0.45712142 0.8975985  0.29448623]
 [0.03888182 0.48158716 0.90749054 0.86892389 0.53423858]]


ValueError: operands could not be broadcast together with shapes (3,) (2,5) 